import type { TierList } from "@/lib/types";

/**
 * Tier lists éditoriales.
 * Les `slug` doivent correspondre à ceux des données générées ; les entrées
 * inconnues sont ignorées silencieusement à l'affichage (validées par `npm run typecheck`
 * et par le script de vérification `scripts/check-content.mjs`).
 */
export const TIER_LISTS: TierList[] = [
  {
    game: "hsr",
    mode: "moc",
    label: "Memory of Chaos",
    description:
      "Évaluation sur le contenu à étages : capacité à effacer deux vagues dans le temps imparti, avec un support adapté.",
    updated: "2026-07-20",
    entries: [
      { slug: "acheron", tier: "S+", note: "DPS Néant sans égal en équipe mono-Néant, ultime à charge rapide." },
      { slug: "firefly", tier: "S+", note: "Cœur des compositions Break Feu, dégâts de rupture massifs." },
      { slug: "the-herta", tier: "S+", note: "DPS AoE dominant sur les vagues denses." },
      { slug: "sunday", tier: "S+", note: "Buffeur d'invocations et d'ultimes, relance immédiate." },
      { slug: "robin", tier: "S+", note: "Meilleur buffeur d'équipe : ATK%, DMG% et action avancée." },
      { slug: "ruan-mei", tier: "S+", note: "Universelle : vitesse, break et réduction de résistance." },
      { slug: "aventurine", tier: "S", note: "Bouclier fiable et dégâts de suivi corrects." },
      { slug: "huohuo", tier: "S", note: "Soigneuse polyvalente avec régénération d'énergie." },
      { slug: "kafka", tier: "S", note: "Reine du DoT, à jouer avec Black Swan." },
      { slug: "black-swan", tier: "S", note: "Empile l'Arcana, scaling exponentiel sur durée." },
      { slug: "sparkle", tier: "S", note: "Points de compétence infinis pour les DPS gourmands." },
      { slug: "feixiao", tier: "S", note: "DPS mono-cible avec attaques de suivi." },
      { slug: "fu-xuan", tier: "S", note: "Mitigation d'équipe, confort maximal." },
      { slug: "jiaoqiu", tier: "S", note: "Debuffeur Ashen Roast, partenaire naturel d'Acheron." },
      { slug: "lingsha", tier: "S", note: "Soins + break Feu, remplace Gallagher en Firefly." },
      { slug: "topaz-numby", tier: "A", note: "Excellente en attaques de suivi, dépend du duo." },
      { slug: "jingliu", tier: "A", note: "Puissante mais gourmande en soutien dédié." },
      { slug: "boothill", tier: "A", note: "Break mono-cible, nécessite Ruan Mei." },
      { slug: "jade", tier: "A", note: "Sous-DPS de suivi, brille avec The Herta." },
      { slug: "blade", tier: "A", note: "Scaling HP solide mais vieillissant." },
      { slug: "silver-wolf", tier: "A", note: "Implantation de faiblesse, niche mais utile." },
      { slug: "luocha", tier: "A", note: "Soins automatiques sans coût en points de compétence." },
      { slug: "gepard", tier: "B", note: "Bouclier fiable, apport offensif nul." },
      { slug: "clara", tier: "B", note: "Contre-attaques agréables, plafond limité." },
      { slug: "welt", tier: "B", note: "Contrôle correct, dégâts datés." },
      { slug: "himeko", tier: "B", note: "Bonne en Pure Fiction, moyenne ailleurs." },
      { slug: "seele", tier: "B", note: "Mono-cible pure, dépassée par Feixiao." },
      { slug: "bailu", tier: "C", note: "Soins irréguliers, remplacée par Huohuo." },
      { slug: "yanqing", tier: "D", note: "Trop fragile, conditions de buff punitives." },
    ],
  },
  {
    game: "hsr",
    mode: "pf",
    label: "Pure Fiction",
    description: "Vagues d'ennemis en continu : les DPS de zone et les générateurs d'actions écrasent la concurrence.",
    updated: "2026-07-20",
    entries: [
      { slug: "the-herta", tier: "S+", note: "Conçue pour le mode : dégâts AoE en cascade." },
      { slug: "himeko", tier: "S+", note: "Ses suivis se déclenchent en boucle sur les vagues." },
      { slug: "rappa", tier: "S+", note: "Break AoE, nettoie des écrans entiers." },
      { slug: "jade", tier: "S", note: "Dégâts de suivi constants sur toute la largeur." },
      { slug: "argenti", tier: "S", note: "Ultime AoE massif, gestion d'énergie simple." },
      { slug: "robin", tier: "S", note: "Buff global, indispensable au score." },
      { slug: "ruan-mei", tier: "S", note: "Vitesse et rupture pour enchaîner les vagues." },
      { slug: "sparkle", tier: "S", note: "Alimente les DPS en points de compétence." },
      { slug: "jing-yuan", tier: "A", note: "Lightning-Lord dévastateur si l'équipe tient." },
      { slug: "kafka", tier: "A", note: "DoT AoE efficace mais lent à démarrer." },
      { slug: "huohuo", tier: "A", note: "Sustain énergie, confortable." },
      { slug: "acheron", tier: "A", note: "Excellente mais orientée mono-cible." },
      { slug: "firefly", tier: "B", note: "Break mono-cible peu adapté aux vagues." },
      { slug: "feixiao", tier: "B", note: "Mono-cible, hors-sujet ici." },
      { slug: "seele", tier: "B", note: "Resurgence aide un peu, sans plus." },
      { slug: "gepard", tier: "C", note: "Bouclier inutile face à des packs faibles." },
    ],
  },
  {
    game: "gi",
    mode: "abyss",
    label: "Abîme Spiralé",
    description: "Deux équipes complètes, contraintes de temps : on valorise le burst, la réaction et la flexibilité.",
    updated: "2026-07-20",
    entries: [
      { slug: "furina", tier: "S+", note: "Buff de dégâts hors-catégorie, marche dans presque toutes les équipes." },
      { slug: "kaedehara-kazuha", tier: "S+", note: "Regroupement + Swirl + réduction de RES élémentaire." },
      { slug: "neuvillette", tier: "S+", note: "DPS Hydro autonome, s'occupe d'une moitié seul." },
      { slug: "nahida", tier: "S+", note: "Colonne vertébrale de toutes les équipes Dendro." },
      { slug: "arlecchino", tier: "S+", note: "DPS Pyro on-field extrêmement rentable." },
      { slug: "mavuika", tier: "S+", note: "DPS Pyro flexible avec burst mobile." },
      { slug: "bennett", tier: "S+", note: "Buff d'ATK et soins : increvable depuis la 1.0." },
      { slug: "xilonen", tier: "S", note: "Réduction de RES Géo et soutien de rotation." },
      { slug: "raiden-shogun", tier: "S", note: "Batterie d'énergie et dégâts corrects." },
      { slug: "xiangling", tier: "S", note: "Meilleur off-field Pyro du jeu, 4★." },
      { slug: "yelan", tier: "S", note: "Hydro off-field, buff de dégâts progressif." },
      { slug: "kamisato-ayaka", tier: "S", note: "Freeze impeccable avec Kazuha et Shenhe." },
      { slug: "hu-tao", tier: "S", note: "Vaporize dévastateur, exige Yelan/Xingqiu." },
      { slug: "zhongli", tier: "S", note: "Bouclier universel + shred Géo." },
      { slug: "clorinde", tier: "A", note: "Excellente en Aggravate, dépendante du support." },
      { slug: "wriothesley", tier: "A", note: "Cryo mono-cible fiable." },
      { slug: "navia", tier: "A", note: "Géo burst, dépend des cristaux." },
      { slug: "nilou", tier: "A", note: "Bloom exceptionnel mais équipe verrouillée." },
      { slug: "xingqiu", tier: "A", note: "Application Hydro et mitigation, 4★ indémodable." },
      { slug: "kuki-shinobu", tier: "A", note: "Soigneuse Électro pour Hyperbloom." },
      { slug: "eula", tier: "B", note: "Physique puissante mais rotation rigide." },
      { slug: "cyno", tier: "B", note: "Bon en Aggravate, moins flexible." },
      { slug: "ganyu", tier: "B", note: "Charged shots vieillissants." },
      { slug: "diluc", tier: "C", note: "Kit daté, remplacé partout." },
      { slug: "qiqi", tier: "C", note: "Soins solides, aucun apport offensif." },
      { slug: "amber", tier: "D", note: "Utile hors combat uniquement." },
    ],
  },
  {
    game: "gi",
    mode: "theater", 
    label: "Théâtre Imaginarium",
    description: "Le mode récompense la profondeur du compte : les 4★ et les personnages hors-méta reprennent de la valeur.",
    updated: "2026-07-20",
    entries: [
      { slug: "bennett", tier: "S+", note: "Toujours choisi, quel que soit l'élément imposé." },
      { slug: "xiangling", tier: "S+", note: "4★ Pyro imbattable pour remplir les contraintes." },
      { slug: "furina", tier: "S+", note: "S'insère dans toutes les compositions." },
      { slug: "kaedehara-kazuha", tier: "S", note: "Utilitaire universel." },
      { slug: "nahida", tier: "S", note: "Débloque les élements Dendro imposés." },
      { slug: "xingqiu", tier: "S", note: "Hydro off-field disponible pour tous." },
      { slug: "sucrose", tier: "A", note: "Kazuha du pauvre, très correcte." },
      { slug: "fischl", tier: "A", note: "Électro off-field constant." },
      { slug: "kuki-shinobu", tier: "A", note: "Soins + Électro, deux besoins d'un coup." },
      { slug: "collei", tier: "B", note: "Dendro d'appoint quand l'élément est imposé." },
      { slug: "noelle", tier: "B", note: "Géo autonome pour les étages faciles." },
      { slug: "barbara", tier: "C", note: "Application Hydro, fragile." },
    ],
  },
  {
    game: "zzz",
    mode: "shiyu",
    label: "Shiyu Defense",
    description: "Contenu chronométré en duo d'équipes : on note la vitesse de clear, le Stun et la fluidité des rotations.",
    updated: "2026-07-20",
    entries: [
      { slug: "miyabi", tier: "S+", note: "Agent le plus puissant du jeu, anomalie Givre autonome." },
      { slug: "yixuan", tier: "S+", note: "DPS Encre aurique avec sustain intégré." },
      { slug: "astra-yao", tier: "S+", note: "Buffeuse universelle, se glisse dans toutes les équipes." },
      { slug: "evelyn", tier: "S", note: "DPS Feu très régulier, excellente sur boss." },
      { slug: "trigger", tier: "S", note: "Support Électro de rupture, rotation rapide." },
      { slug: "hugo", tier: "S", note: "Anomalie Glace de haut niveau." },
      { slug: "caesar", tier: "S", note: "Bouclier + buff d'impact, sécurise les clears." },
      { slug: "lighter", tier: "S", note: "Stun Feu qui buffe les dégâts critiques." },
      { slug: "zhu-yuan", tier: "S", note: "Éther mono-cible, référence historique." },
      { slug: "jane", tier: "S", note: "Anomalie Physique explosive avec Seth." },
      { slug: "yanagi", tier: "S", note: "Disorder Électro, très forte en double anomalie." },
      { slug: "burnice", tier: "S", note: "Anomalie Feu off-field, universelle." },
      { slug: "qingyi", tier: "A", note: "Stun Électro solide, dépassée par Trigger." },
      { slug: "ellen", tier: "A", note: "DPS Glace fiable mais rotation exigeante." },
      { slug: "lycaon", tier: "A", note: "Stun Glace de référence pour Ellen." },
      { slug: "harumasa", tier: "A", note: "DPS Électro correct, plafond moyen." },
      { slug: "rina", tier: "A", note: "Support Électro à pénétration." },
      { slug: "soukaku", tier: "A", note: "Buffeuse Glace 4★, indispensable en budget." },
      { slug: "nicole", tier: "A", note: "Regroupe les ennemis et réduit la défense." },
      { slug: "grace", tier: "B", note: "Anomalie Électro remplacée par Yanagi." },
      { slug: "koleda", tier: "B", note: "Stun Feu, tempo difficile." },
      { slug: "soldier-11", tier: "B", note: "DPS Feu daté." },
      { slug: "lucy", tier: "B", note: "Buff d'ATK simple et efficace." },
      { slug: "piper", tier: "C", note: "Anomalie Physique, ciblage aléatoire." },
      { slug: "anby", tier: "C", note: "Stun 4★ de démarrage." },
      { slug: "billy", tier: "D", note: "Peu de dégâts, contenu précoce uniquement." },
    ],
  },
  {
    game: "zzz",
    mode: "da",
    label: "Deadly Assault",
    description: "Boss uniques à score : les dégâts mono-cible bruts et les fenêtres de Stun font toute la différence.",
    updated: "2026-07-20",
    entries: [
      { slug: "miyabi", tier: "S+", note: "Score maximal quasi garanti." },
      { slug: "evelyn", tier: "S+", note: "Excellente sur cible unique immobile." },
      { slug: "yixuan", tier: "S+", note: "Burst mono-cible énorme." },
      { slug: "astra-yao", tier: "S", note: "Buff constant, augmente tous les scores." },
      { slug: "trigger", tier: "S", note: "Fenêtres de Stun rallongées." },
      { slug: "zhu-yuan", tier: "S", note: "Bourrine les boss à faiblesse Éther." },
      { slug: "lighter", tier: "S", note: "Amplifie les dégâts pendant le Stun." },
      { slug: "hugo", tier: "S", note: "Anomalie Glace au-dessus du lot." },
      { slug: "ellen", tier: "A", note: "Bonne, sous réserve d'un bon Stun." },
      { slug: "jane", tier: "A", note: "Fort en durée, moins en burst." },
      { slug: "qingyi", tier: "A", note: "Stun régulier." },
      { slug: "caesar", tier: "A", note: "Sécurise les phases de contre-attaque." },
      { slug: "soukaku", tier: "B", note: "Buff Glace budget." },
      { slug: "koleda", tier: "B", note: "Stun correct sur boss lents." },
      { slug: "piper", tier: "C", note: "Dégâts dispersés." },
    ],
  },
];

export function getTierList(game: string, mode: string) {
  return TIER_LISTS.find((list) => list.game === game && list.mode === mode);
}

export function getTierListsForGame(game: string) {
  return TIER_LISTS.filter((list) => list.game === game);
}
